### ISSUE TITLE
502 Bad Gateway / Explore Biblical Quotations in Newspapers

### ISSUE THREAD

**Issue by silviaegt** [public-bible/quotation-finder#22]
Hi Lincoln!

I'm a great fan of your DH projects, and wanted to use your America's Public Bible website as an example for my history students. Unfortunately, the "[Explore Biblical Quotations](http://americaspublicbible.org/exploration.html)" page seems to be down, and I wanted to let you know.

All best,

S.

**Comment by lmullen** [comment]
@silviaegt Thanks for letting me know (and for the kinds words). The site is back up.
